{% set name = "nd2-dask" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nd2_dask-{{ version }}.tar.gz
  sha256: e54fb71de99f5884d2d5f18567784ef4fa87a0122d100e0a5b8fc7ab609703e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - dask-core
    - napari-plugin-engine >=0.1.4
    - nd2reader
    - numpy
    - python >=3.6,<3.10
    - toolz
    - vispy

test:
  imports:
    - nd2_dask
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DragaDoncila/nd2-dask
  summary: Plugin to load nd2 data into napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - DragaDoncila
    - jni
